name: Linux Build
#
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install deps
      run: |
       sudo apt-get update
       sudo apt-get install libboost-all-dev libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libx11-xcb-dev libxcb-image0-dev libxrandr-dev libxcb-randr0-dev libudev-dev libfreetype6-dev libglew-dev libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libjpeg62 libxcursor-dev cmake libclang-dev clang
       
    - name: Install SFML
      run: |
       set -e
       mkdir sfml_install
       wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip --no-check-certificate
       unzip -q SFML-2.5.1-sources.zip
       pushd SFML-2.5.1 && mkdir build && cd build && cmake .. && make
       make DESTDIR=$GITHUB_WORKSPACE/sfml_install install
       popd

       
    - name: Build Boost
      uses: egor-tensin/build-boost@v1.4
      id: boost
      with:
        version: 1.81.0
        libraries: log filesystem program_options system
        platform: x64
        toolset: gcc
        configuration: Debug

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Debug
