name: Build with Boost

on:
  push:
    branches:
      - master  # Adjust branch name as needed
  pull_request:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Visual Studio 2019 Build Tools
        run: |
          # Download Visual Studio 2019 Build Tools installer
          Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vs_buildtools.exe' -OutFile 'vs_buildtools.exe'

          # Install Visual Studio 2019 Build Tools
          Start-Process -Wait -FilePath '.\vs_buildtools.exe' -ArgumentList '--quiet', '--norestart', '--nocache', '--installPath', 'C:\BuildTools', '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VCTools', '--includeRecommended', '--includeOptional'

      - name: Set up MSBuild environment
        run: |
          echo "PATH=C:\BuildTools\MSBuild\Current\Bin;%PATH%" >> $GITHUB_ENV
          echo "VS140COMNTOOLS=C:\BuildTools\Common7\Tools" >> $GITHUB_ENV
          echo "VS160COMNTOOLS=C:\BuildTools\Common7\Tools" >> $GITHUB_ENV

      - name: Install Boost
        run: |
          # Download Boost 1.81.0
          Invoke-WebRequest -Uri 'https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.zip' -OutFile 'boost_1_81_0.zip'

          # Extract Boost
          Expand-Archive -Path 'boost_1_81_0.zip' -DestinationPath 'boost_1_81_0'

          # Build and install Boost
          cd 'boost_1_81_0'
          .\bootstrap.bat

          # Adjust b2 command based on MSVC version
          if (Test-Path 'C:\BuildTools\VC\Auxiliary\Build\vcvars64.bat') {
            . 'C:\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
          }
          else {
            . 'C:\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' x64
          }

          .\b2.exe -j%NUMBER_OF_PROCESSORS% --build-dir=build64 --address-model=64 --build-type=complete --with-system --with-date_time --with-filesystem --with-iostreams --with-program_options install

      - name: Build project
        run: |
          msbuild /m /p:Configuration=Release CAI.sln
