name: Build with Boost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Visual Studio 2019 Build Tools
        run: |
          # Download Visual Studio 2019 Build Tools installer
          curl -L -o vs_buildtools.exe https://aka.ms/vs/16/release/vs_buildtools.exe

          # Install Visual Studio 2019 Build Tools
          start /wait vs_buildtools.exe --quiet --wait --norestart --nocache `
            --add Microsoft.VisualStudio.Workload.MSBuildTools `
            --add Microsoft.VisualStudio.Workload.VCTools `
            --includeRecommended `
            --includeOptional

      - name: Install Boost
        run: |
          # Download Boost 1.81.0
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.zip
          unzip boost_1_81_0.zip
          cd boost_1_81_0

          # Build and install Boost
          bootstrap.bat
          b2.exe -j%NUMBER_OF_PROCESSORS% --build-dir=build64 --toolset=msvc address-model=64 install

      - name: Build project
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" `
            /m /p:Configuration=Release CAI.sln
