name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Cache Visual Studio Build Tools installer
        uses: actions/cache@v2
        with:
            path: vs_buildtools.exe
            key: ${{ runner.os }}-buildtools-${{ hashFiles('vs_buildtools.exe') }}
      
      - name: Install SFML
        uses: oprypin/install-sfml@v1
        
      - name: Checkout repository
        uses: actions/checkout@v3

     

      - name: Install Visual Studio 2019 Build Tools
        run: |
          # Download Visual Studio 2019 Build Tools installer
          Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vs_buildtools.exe' -OutFile 'vs_buildtools.exe'

          # Install Visual Studio 2019 Build Tools
          Start-Process -Wait -FilePath '.\vs_buildtools.exe' -ArgumentList '--quiet', '--norestart', '--nocache', '--installPath', 'C:\BuildTools', '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VCTools', '--includeRecommended', '--includeOptional'

          
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1   
        
      - name: Build Boost dynamic
        uses: egor-tensin/build-boost@v1.4
        id: boost
        with:
          version: 1.81.0
          libraries: log filesystem program_options system
          platform: x64
          toolset: msvc142
          configuration: Debug
        
      - name: Build project
        run: |
          msbuild /m /p:Configuration=Release CAI.sln
          
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest

      - name: Run VSTest
        id: run_vstest
        working-directory: x64\Release\
        run: vstest.console.exe /Platform:x64 .\CAI_UnitTest.dll
