name: Build with Boost

on:
  push:
    branches:
      - master  # Adjust branch name as needed
  pull_request:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Visual Studio 2019 Build Tools
        run: |
          # Download Visual Studio 2019 Build Tools installer
          wget https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile vs_buildtools.exe

          # Install Visual Studio 2019 Build Tools
          Start-Process -Wait -FilePath .\vs_buildtools.exe -ArgumentList '--quiet', '--norestart', '--nocache', '--installPath', 'C:\BuildTools', '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VCTools', '--includeRecommended', '--includeOptional'

      - name: Set up MSBuild environment
        run: |
          echo '##[set-env name=PATH;]C:\BuildTools\MSBuild\Current\Bin;$env:PATH'
          echo '##[set-env name=VS140COMNTOOLS;]C:\BuildTools\Common7\Tools'
          echo '##[set-env name=VS160COMNTOOLS;]C:\BuildTools\Common7\Tools'

      - name: Install Boost
        run: |
          # Download Boost 1.81.0
          wget https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.zip
          unzip boost_1_81_0.zip
          cd boost_1_81_0

          # Build and install Boost
          bootstrap.bat
          b2.exe -j%NUMBER_OF_PROCESSORS% --build-dir=build64 --toolset=msvc address-model=64 install

      - name: Build project
        run: |
          msbuild /m /p:Configuration=Release CAI.sln
