name: Build with Boost

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

     # - name: Cache MSVC tools
     #   uses: actions/cache@v2
     #   with:
     #     path: C:\BuildTools
     #     key: msvc-tools

     # - name: Install Visual Studio 2019 Build Tools
     #   run: |
     #     # Download Visual Studio 2019 Build Tools installer
     #     Invoke-WebRequest -Uri 'https://aka.ms/vs/16/release/vs_buildtools.exe' -OutFile 'vs_buildtools.exe'

          # Install Visual Studio 2019 Build Tools
      #    Start-Process -Wait -FilePath '.\vs_buildtools.exe' -ArgumentList '--quiet', '--norestart', '--nocache', '--installPath', 'C:\BuildTools', '--add', 'Microsoft.VisualStudio.Workload.MSBuildTools', '--add', 'Microsoft.VisualStudio.Workload.VCTools', '--includeRecommended', '--includeOptional'

      - name: Set up MSBuild environment
        run: |
          echo "PATH=C:\BuildTools\MSBuild\Current\Bin;%PATH%" >> $GITHUB_ENV
          echo "VS140COMNTOOLS=C:\BuildTools\Common7\Tools" >> $GITHUB_ENV
          echo "VS160COMNTOOLS=C:\BuildTools\Common7\Tools" >> $GITHUB_ENV
          
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Install Boost
        run: |
          # Download Boost 1.81.0
          Invoke-WebRequest -Uri 'https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.zip' -OutFile 'boost_1_81_0.zip'
          # Extract Boost
          Expand-Archive -Path 'boost_1_81_0.zip' -DestinationPath 'D:\a\AgentTown\AgentTown>Microsoft Windows'
          # Change to the Boost directory
          Set-Location -Path 'boost_1_81_0'
   
      - name: run bootstrap
        run: |
          cmd.exe "cd boost_1_81_0"
          cmd.exe "dir"
          ./bootstrap.bat
      - name: runb2
        run: |
          b2.exe
          # Return to the project directory
          Set-Location -Path $env:GITHUB_WORKSPACE

      - name: Build project
        run: |
          msbuild /m /p:Configuration=Release CAI.sln
